version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - image_templates:
    - "ghcr.io/m-persic/{{ .ProjectName }}:latest"
    - "ghcr.io/m-persic/{{ .ProjectName }}:{{ .Version }}"
    ids:
      - "comp6231-assignment-02"
sboms:
  - artifacts: archive
checksum:
  name_template: "checksums.txt"
