apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: fmp-service
  name: fmp-service
  namespace: comp6231
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: fmp-service
  type: NodePort
status:
  loadBalancer: {}
