apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ftp-service
  name: ftp-service
  namespace: comp6231
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    run: ftp-service
  type: NodePort
status:
  loadBalancer: {}
