name: release-go

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  release-go:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: GitHub Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      -
        name: Set Up Syft
        uses: anchore/sbom-action/download-syft@0.20.4 
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2
          args: release
      - uses: actions/attest-build-provenance@v2
        with:
          subject-checksums: ./dist/checksums.txt